services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=main
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - ./resources/db-migrations:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql-data: